### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by hernancx09** [hernancx09/UWA_CITS_3402_Project#11]
Registration form is currently taking in the following:
- Username
- Password
- Confirm Password
New Pull request changes it to this:
- Username
- Display Name
- Password
- Confirm Password

Wouldnt it be easier to just align our registration model with current industry norms like this:
- Name (First and Last)
- Email
- Password
- Confirm Password

And following up, Login as we have it takes in Username and Password, but why not make it Email and Password? this would also help with the future implementation of account recovery, Email updates with new job postings, etc.

**Comment by UwaProj** [comment]
We can use emails, but then we will have to have checks for email address validity. If we can do that then emails would be better

**Comment by sandoncj** [comment]
Agreed. We should change it to email and names. Time permitting we can introduce account recovery otherwise it can be for future updates

**Comment by hernancx09** [comment]
Flask has the necessary email validators for forms so I dont think that part should be too much of a hassle.  Glad we are all on the same page

**Comment by sandoncj** [comment]
Correct. All changes should be incorporated now in the pull request. Closing this issue
