### ISSUE TITLE
Separate main functionality

### ISSUE THREAD

**Issue by sandoncj** [hernancx09/UWA_CITS_3402_Project#15]
I think we should separate mains jobs posts and looking for work posts into their own pages/endpoints. This will allow us to display more data to the user.

**Comment by UwaProj** [comment]
my concern is that the page might look quite barren if we only have a single table on the page and separate them.

**Comment by sandoncj** [comment]
only whilst the database is empty. Otherwise we will be overflowing after about a maximum 5-10 posts

**Comment by UwaProj** [comment]
i guess it would allow users to focus more on a single type of job post if we split them. but what happens if we ever get lets say 40 posts or whatever is enough to overflow the table, will we have a page cap?

**Comment by sandoncj** [comment]
We have handle overflows at some point yes, having a larger space to work with just means that we can present more entries to the user at one time.

**Comment by UwaProj** [comment]
gotcha, ok we'll monitor the design of the page as we develop then, as long as it doesnt look too empty, we can separate out the pages. no problem.
