### ISSUE TITLE
Remove status?

### ISSUE THREAD

**Issue by sandoncj** [hernancx09/UWA_CITS_3402_Project#22]
status seems like redundant information. If the post is up then the job is open

**Comment by UwaProj** [comment]
My concern is that there might be jobs with multiple people joining it or multiple openings or jobs that are going weekly, such as the weekly microvolunteering done in UWA. any thoughts?

**Comment by sandoncj** [comment]
At the moment I feel like we should leave the status of a job opening up to the poster. They can remove their post once they have enough applicants or have chosen a suitable candidate. Future updates could include an automatic repost feature, that allows a user to open a job weekly etc

**Comment by UwaProj** [comment]
noted. that sounds good for now then. we can do away with job status for now then.
