### ISSUE TITLE
Styling issues with the Jobs Page

### ISSUE THREAD

**Issue by EP-Wick** [hernancx09/UWA_CITS_3402_Project#23]
It seems that some CSS styling that is implemented for the View_Jobs page is affecting the main Jobs page. New classes would need to be created or reverted to potentially fix the issue.

**Comment by sandoncj** [comment]
Yeh definitely by creating new classes and/or IDs for the new divs and reverting the existing ones to previous versions you should be able to rectify the issue

**Comment by EP-Wick** [comment]
Successfully separated the class names in order to add styling to individual files
