### ISSUE TITLE
minor issues.

### ISSUE THREAD

**Issue by UwaProj** [hernancx09/UWA_CITS_3402_Project#38]
When viewing My applications under the profile page, even though i already submitted my application for a job.  when i click view on that, i can currently still see the apply button at the bottom of the page. this means that i can reapply for the same job again and write a new message. maybe it would be better if it was hidden? 

in the view page in jobs, after applying for a job in the modal and clicking apply, it takes us back to the view page, it might be better if it takes us back to the initial jobs page.

**Comment by sandoncj** [comment]
good calls Ames, ill get onto fixing them now
