### ISSUE TITLE
Jobs Page post Log in vs Log out state

### ISSUE THREAD

**Issue by hernancx09** [hernancx09/UWA_CITS_3402_Project#45]
When you make a post, while still logged in the post isnt appearing for me in the jobs page, only when I log out does it appear.

I tried logging back in and it disappeared again, but I can still see it in my profile.

so to sum up:
Logged in-
- made post
- cant see it on job board but I can on my profile
Logged out- 
- I can see the job post in the job board

**Comment by hernancx09** [comment]
I made a different account and I could see the post on that one when I was logged in. So only when logged in to the same account you posted it from, it doesnt appear on the jobs page. Is this on purpose since you can see it on your profile or a bug?

**Comment by sandoncj** [comment]
No this is on purpose. We figured there's not really any reason for people to see their own posts on the main jobs page.
